# Generated by Django 4.2.23 on 2025-11-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0215_add_magazine_permission'),
        ('judge', '0215_merge_20251123_1130'),
    ]

    operations = [
    ]
