# Generated by Django 4.2.30 on 2026-06-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0214_alter_contest_authors_alter_contest_curators_and_more'),
        ('judge', '0227_add_submission_heatmap_index'),
    ]

    operations = [
    ]
